### ISSUE TITLE
Net::HTTP inherited loading bug

### ISSUE THREAD

**Issue by daniel-barrows** [TwilightCoders/rubysu#2]
When the parent script loads the `net/http` library, the Sudo::Wrapper appears to improperly inherit this dependency, and throws the following error upon start!:

```
(drbunix:/tmp/rubysu-26896-76952480) /usr/lib/ruby/2.3.0/net/http/requests.rb:8:in `<top (required)>': uninitialized constant Net::HTTP (NameError)
Did you mean?  Net::HTTPNotImplemented
               Net::HTTPMultipleChoice
[... lots more ...]
               Net::HTTP [Ironically]
	from (drbunix:/tmp/rubysu-26896-76952480) ~/.gem/ruby/2.3.0/gems/sudo-0.1.1/lib/sudo/proxy.rb:17:in `require'
	from (drbunix:/tmp/rubysu-26896-76952480) ~/.gem/ruby/2.3.0/gems/sudo-0.1.1/lib/sudo/proxy.rb:17:in `proxy'
	from (drbunix:/tmp/rubysu-26896-76952480) /usr/lib/ruby/2.3.0/drb/drb.rb:1624:in `perform_without_block'
	from (drbunix:/tmp/rubysu-26896-76952480) /usr/lib/ruby/2.3.0/drb/drb.rb:1584:in `perform'
	from (drbunix:/tmp/rubysu-26896-76952480) /usr/lib/ruby/2.3.0/drb/drb.rb:1657:in `block (2 levels) in main_loop'
	from (drbunix:/tmp/rubysu-26896-76952480) /usr/lib/ruby/2.3.0/drb/drb.rb:1653:in `loop'
	from (drbunix:/tmp/rubysu-26896-76952480) /usr/lib/ruby/2.3.0/drb/drb.rb:1653:in `block in main_loop'
	from ~/.gem/ruby/2.3.0/gems/sudo-0.1.1/lib/sudo/wrapper.rb:90:in `block in load_features'
	from ~/.gem/ruby/2.3.0/gems/sudo-0.1.1/lib/sudo/wrapper.rb:89:in `each'
	from ~/.gem/ruby/2.3.0/gems/sudo-0.1.1/lib/sudo/wrapper.rb:89:in `load_features'
	from ~/.gem/ruby/2.3.0/gems/sudo-0.1.1/lib/sudo/wrapper.rb:79:in `start!'
```

A workaround is to explicitly load `net/http` like this:

    Sudo::Wrapper.run('-rnet/http')

It appears that the problem is because Sudo is loading net/http/requests.rb _before_ net/http.rb.

**Comment by daniel-barrows** [comment]
I wrote some code to demonstrate the issue:

```ruby
require 'net/http'
require 'sudo'

def test_sudo(sudo)
  puts "NOTE: Preparing sudo.start! with opt #{sudo.instance_variable_get('@ruby_opts')}"
  sudo.start!
  puts "NOTE: sudo.start! was successful with opt #{sudo.instance_variable_get('@ruby_opts')}"
  sudo.stop!
end

test_sudo(Sudo::Wrapper.new('-rnet/http'))
test_sudo(Sudo::Wrapper.new)
```
On my machine, the first test_sudo works, but the second one doesn't. This produces this:

> NOTE: Preparing sudo.start! with opt -rnet/http
> NOTE: sudo.start! was successful with opt -rnet/http
> NOTE: Preparing sudo.start! with opt 
> (drbunix:/tmp/rubysu-1245-81603330) /usr/lib/ruby/2.3.0/net/http/requests.rb:8:in `<top (required)>': uninitialized constant Net::HTTP (NameError)

**Comment by gderosa** [comment]
Hi @daniel-barrows, thanks for for your report. Good to see the gem is still used around! It's been years since I've worked on it last time! If you have a PR to fix this that's more than welcome, otherwise I have to find a moment to look into this. In fact this is looking for a maintainer, unless things changes in my work and I can re-focus on Ruby. Nonetheless, I'll see what I can do, and thanks for the suggestion.

**Comment by voltechs** [comment]
I got a similar error recently. At first I thought it was Ruby's `2.5.0` change in finding constants, but it looks like OP is using `2.3.0`, so that's clearly not the issue.

(My personal silver lining—I had _no idea_ Ruby had `DRb`, it would solve something I was trying to accomplish a while back and couldn't find anything on.)

```NameError: uninitialized constant Bundler::CLI
Did you mean?  Bundler::CLI
               CGI
  (drbunix:/tmp/rubysu-18432-70193579218620) ~/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/cli/common.rb:4:in `<module:Bundler>'
  (drbunix:/tmp/rubysu-18432-70193579218620) ~/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/cli/common.rb:3:in `<top (required)>'
  (drbunix:/tmp/rubysu-18432-70193579218620) ~/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sudo-0.1.1/lib/sudo/proxy.rb:17:in `require'
  (drbunix:/tmp/rubysu-18432-70193579218620) ~/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sudo-0.1.1/lib/sudo/proxy.rb:17:in `proxy'
  (drbunix:/tmp/rubysu-18432-70193579218620) ~/.rbenv/versions/2.5.1/lib/ruby/2.5.0/drb/drb.rb:1630:in `perform_without_block'
  (drbunix:/tmp/rubysu-18432-70193579218620) ~/.rbenv/versions/2.5.1/lib/ruby/2.5.0/drb/drb.rb:1590:in `perform'
  (drbunix:/tmp/rubysu-18432-70193579218620) ~/.rbenv/versions/2.5.1/lib/ruby/2.5.0/drb/drb.rb:1674:in `block (2 levels) in main_loop'
  (drbunix:/tmp/rubysu-18432-70193579218620) ~/.rbenv/versions/2.5.1/lib/ruby/2.5.0/drb/drb.rb:1670:in `loop'
  (drbunix:/tmp/rubysu-18432-70193579218620) ~/.rbenv/versions/2.5.1/lib/ruby/2.5.0/drb/drb.rb:1670:in `block in main_loop'
  ~/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sudo-0.1.1/lib/sudo/wrapper.rb:90:in `block in load_features'
  ~/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sudo-0.1.1/lib/sudo/wrapper.rb:89:in `each'
  ~/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sudo-0.1.1/lib/sudo/wrapper.rb:89:in `load_features'
  ~/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sudo-0.1.1/lib/sudo/wrapper.rb:79:in `start!'
  ~/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sudo-0.1.1/lib/sudo/wrapper.rb:28:in `run'
...
```

**Comment by daniel-barrows** [comment]
Ruby adds scripts to $LOADED_FEATURES in the order that they complete loading. Although this behavior isn't defined in the [Kernel#require spec](https://github.com/ruby/ruby/blob/trunk/spec/ruby/core/kernel/shared/require.rb), I regard this behavior is correct, because it assures you that anything in $LOADED_FEATURES is available to your current script. Usually, this is in order of dependency, because scripts load their dependencies at the top of the script, before they execute. 

However, some libraries, such as net/http.rb, load additional features [at the bottom of the script](https://github.com/ruby/ruby/blob/ruby_2_5/lib/net/http.rb#L1630). These additional features depend on net/http.rb being loaded, even though it wasn't added to $LOADED_FEATURES before they were executed because net/http.rb hadn't finished loading.

This causes a problem for Ruby Sudo, because Ruby Sudo needs to know what order to [load files](https://github.com/gderosa/rubysu/blob/master/lib/sudo/wrapper.rb#L86) in for it's DRb instance. However, this isn't just a problem for Ruby Sudo. It is also a problem for any script which attempts to load a library component explicitly. Ruby Sudo only fails in cases where requiring a script would fail in any other script, eg. <code>require '[net/http/requests](https://github.com/ruby/ruby/blob/ruby_2_5/lib/net/http/requests.rb)'</code>.

There are two ways to modify libraries to fix this problem:
1. **Dynamically load the whole library as needed.**
   At the top of net/http/requests.rb and other library components, add:

       require 'net/http' unless defined?(Net::HTTP)

   This option is
   1. Future-proof. The library could later be rewritten so that net/http/requests.rb can be loaded separately from the rest of net/http
   2. Avoids circular linking. This will not be invoked if net/http is already being loaded.
   3. Allows substitution. Another library could define its own Net::HTTP different from the version in net/http.rb, and invoke this library to gain its features, without having a collision with net/http
2. **Pull core into a separate file.**
   Move the substance of net/http.rb into net/http/core.rb. leaving net/http.rb as simply a list of require statements, starting with net/http/core.
    This is the easier, but lacks the advantages of option 1.

I'll have a patch for Ruby Sudo ready shortly.

**Comment by gderosa** [comment]
@daniel-barrows, @voltechs, thank you both! It's great to see there's a community of users and contributors. 

@voltechs, I see you have sent a [PR](https://github.com/gderosa/rubysu/pull/3), by mistake, but I mean: feel free to continue your work and reopen it or send another one as soon as it's ready!

@daniel-barrows, feel free to submit your stuff as well :)

I'm probably better at giving an opinion on all this once I see your ideas implemented as code :wink: 

Thank you again.

Guido

**Comment by voltechs** [comment]
Hey all, got [my PR up](https://github.com/gderosa/rubysu/pull/4). I know it breaks the API, but we're talking `0.0.3` so anything goes :P

Another idea I had for the future of the gem is allowing explicit "requires" inside the wrapper block.

```ruby
Sudo::Wrapper.run do |sudo|
  sudo.require 'some_explicit/gem'
  sudo[File].open('/tmp/whatever')
end
```

**Comment by voltechs** [comment]
@daniel-barrows will you give `master` a shot and see if the issue you were experiencing is fixed? I think @gderosa is planning to release a new version of the gem soon too.

**Comment by gderosa** [comment]
@daniel-barrows, @voltechs, yes a new version of the gem is now available ([0.2.0](https://rubygems.org/gems/sudo)).

See also https://github.com/gderosa/rubysu/pull/8.

**Comment by gderosa** [comment]
Not having response from @daniel-barrows , I'm assuming issue is fixed by now, after the contribution from @voltechs . Feel free to reopen or open a new one if this is an issue again. Thanks!

**Comment by yelvert** [comment]
This broke my app, nothing gets loaded correctly anymore. I originally monkeypatched the `load_features` method like this to solve this problem.

```
class Sudo::Wrapper
  def load_features
    @proxy.proxy Kernel, :require, Bakery.project.root.join('project.rb')
    @proxy.proxy Bakery, :eager_load!
    unless $LOADED_FEATURES == @loaded_features
      new_features = $LOADED_FEATURES - @loaded_features
      new_features.each do |feature|
        begin
          @proxy.proxy Kernel, :require, feature
        rescue NameError => err
          begin
            @proxy.proxy Kernel, :require, err.missing_name.underscore
          rescue NameError
            raise err
          end
        end
        @loaded_features << feature
      end
    end
  end
end
```

Notice the `require` and `eager_load!` at the top, that `eager_load!` is from `ActiveSupport::Autoload`. Also, in
```
        rescue NameError => err
          begin
            @proxy.proxy Kernel, :require, err.missing_name.underscore
          rescue NameError
            raise err
          end
        end
```
is a terrible way to handle it, but it has worked flawlessly for me, handling everything from net/http to pry and yardoc.

At first, I thought this PR was going to be great, I just remove that whole monkey patch and add 2 lines to my Sudo::Wrapper like so,
```
          def _run
            if sudo?
              Sudo::Wrapper.run do |sudo|
                sudo[Kernel].require Bakery.project.root.join('project.rb')
                sudo[Bakery].eager_load!
                sudo[self].run
              end
            else
              run
            end
          end
```
but now, my app doesn't even boot inside the wrapper because of the following error on the `eager_load!`:

```
/Users/yelvert/.rvm/gems/ruby-2.4.4/gems/activesupport-5.2.2/lib/active_support/core_ext/marshal.rb:6:in `load': class Bundler::StubSpecification needs to have method `_load' (TypeError)
        from /Users/yelvert/.rvm/gems/ruby-2.4.4/gems/activesupport-5.2.2/lib/active_support/core_ext/marshal.rb:6:in `load'
        from /Users/yelvert/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/drb/drb.rb:594:in `block in load'
        from /Users/yelvert/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/drb/drb.rb:590:in `synchronize'
        from /Users/yelvert/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/drb/drb.rb:590:in `load'
        from /Users/yelvert/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/drb/drb.rb:642:in `recv_reply'
        from /Users/yelvert/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/drb/drb.rb:941:in `recv_reply'
        from /Users/yelvert/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/drb/drb.rb:1254:in `send_message'
        from /Users/yelvert/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/drb/drb.rb:1142:in `block (2 levels) in method_missing'
        from /Users/yelvert/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/drb/drb.rb:1229:in `open'
        from /Users/yelvert/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/drb/drb.rb:1141:in `block in method_missing'
        from /Users/yelvert/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/drb/drb.rb:1160:in `with_friend'
        from /Users/yelvert/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/drb/drb.rb:1140:in `method_missing'
        from /Users/yelvert/.rvm/gems/ruby-2.4.4/gems/sudo-0.2.0/lib/sudo/wrapper.rb:134:in `prospective_gems'
        from /Users/yelvert/.rvm/gems/ruby-2.4.4/gems/sudo-0.2.0/lib/sudo/wrapper.rb:140:in `load_gems'
        from /Users/yelvert/.rvm/gems/ruby-2.4.4/gems/sudo-0.2.0/lib/sudo/wrapper.rb:126:in `load!'
        from /Users/yelvert/.rvm/gems/ruby-2.4.4/gems/sudo-0.2.0/lib/sudo/wrapper.rb:103:in `[]'
```

I also confirmed that ^ is not `ActiveSupport::MarshalWithAutoloading`s fault by leaving out that core extension, same error.

After further reading of the current solution in 2.0.0, the new`load_gems` completely ignores everything that's been required inside your local project, so, while it may handle loading all the gems you've loaded, it doesn't handle a file in your project doing `require_relative` or `require File.expand_path(File.join('lib', 'foo', 'bar'), _dir_)`. All of this makes the need for something like `ActiveSupport::Autoload`s `eager_load!` even more important to work. BTW this is not a rails project, I'm just using `ActiveSupport` and `ActiveModel`.

**Comment by voltechs** [comment]
Hey @yelvert,

Thanks for reporting this.

Would you mind opening a new issue with this information. We’ve addressed and closed this issue and the fix has been out for a while now, so this is a new issue.

Also, if you could make a spec that reproduces your issue, that would be a huge help for a maintainer here to get a fix out for you.

**Comment by gderosa** [comment]
@voltechs can you please contact me (guidoderosa at gmail) and tell me the email/username you use on rubygems.org ? You already have write access here, I would like to give you upload access to rubygems. You're de-facto a co-maintainer, if not _the_ maintainer now :) and I have little time to dedicate to this project right now. Thanks, also for the prompt response to this bug report. Good to see an active community of users continues, and sorry if something is broken.
